### ISSUE TITLE
Install Failure :(

### ISSUE THREAD

**Issue by wxprofessor** [schachmat/wego#100]
user@box:~/go$ go get github.com/schachmat/wego
# github.com/schachmat/ingo
src/github.com/schachmat/ingo/in.go:134: undefined: flag.UnquoteUsage
user@box:~/go$ go install github.com/schachmat/wego
# github.com/schachmat/ingo
src/github.com/schachmat/ingo/in.go:134: undefined: flag.UnquoteUsage

**Comment by schachmat** [comment]
See here: schachmat/ingo#2
