### ISSUE TITLE
Add date and time to current weather info?

### ISSUE THREAD

**Issue by StarsoftAnalysis** [schachmat/wego#103]
It would be nice if the current weather information included the date and time for the selected location, mainly for when I'm checking the weather in some other part of the world.

**Comment by schachmat** [comment]
Heyho @StarsoftAnalysis,

getting and displaying the time of a specific location is not the main goal of a weather application. However if there are more people interested in this, I'll consider it.

**Comment by schachmat** [comment]
Closing since there was only one thumbs-up. :disappointed:

**Comment by Silent-Hunter** [comment]
I too would like this, as I currently run wego using cron every 30 minutes, and I'd like to be able to see when it last checked. I currently do this with the date command running before wego each time, but it'd be nice to have it inside the wego output.
