### ISSUE TITLE
Worldweatheronline has free API keys again

### ISSUE THREAD

**Issue by ghost** [schachmat/wego#105]
I was able to get a free api-key via [Apixu](https://www.apixu.com/) which is promoted on the worldweatheronline website.

[Documentation ](https://www.apixu.com/doc/) to the new api service.

On my personal dashboard there are some example links to use the api aswell (http & https):

Current Weather:
https://api.apixu.com/v1/current.json?key=<MYKEY>&q=Paris 
Forecast Weather:
https://api.apixu.com/v1/forecast.json?key=<MYKEY>&q=Paris

Also the new keys wont work with the old configuration.

**Comment by likrtr** [comment]
Apixu moved to a new domain (https://weatherstack.com/)
[Docs to the service](https://weatherstack.com/documentation)
API examples:
Current Weather:
https://api.weatherstack.com/current?access_key=YOUR_ACCESS_KEY&query=New York
Weather Forecast:
https://api.weatherstack.com/forecast?access_key=YOUR_ACCESS_KEY&query=New York&forecast_days=1&hourly=1

**Comment by kordianbruck** [comment]
Happy take pull request to add this backend. If you want to pick this up, feel free to reopen this bug.
