### ISSUE TITLE
Explain in documentation why there are two temperatures.

### ISSUE THREAD

**Issue by deragon** [schachmat/wego#107]
Current weather is reported as follow:

          \  /       Partly cloudy
        _ /"".-.     -19 – -12 °C
          \_(   ).   ↘ 15 km/h
          /(___(__)  14 km
                     0.0 mm

What temperature is it currently?  -19 °C or -12 °C?  It is not clear; this should be documented, or fixed.

**Comment by schachmat** [comment]
For developers it was already documented: https://godoc.org/github.com/schachmat/wego/iface#Cond

I updated the README as well now, thanks for the hint.
