### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by rpmohn** [schachmat/wego#108]
I'm getting an error while trying to update. The version of wego I have now is dated 04-Oct-2015, and is working, but I'd like to get the latest.   

````
$ go get -u github.com/schachmat/wego
# github.com/schachmat/ingo
src/github.com/schachmat/ingo/in.go:134: undefined: flag.UnquoteUsage
````
```
$ go version
go version go1.2.1 linux/amd64
```

**Comment by schachmat** [comment]
See here: schachmat/ingo#2

Sorry for the delay.
