### ISSUE TITLE
forecast.io backend: time slot conversion is wrong and shifts depending on time zone

### ISSUE THREAD

**Issue by crmackay** [schachmat/wego#109]
Just comparing the wego reported forcast temps to the forcast.io website shows a difference. Not sure why, haven't done too much digging yet. Might be the data from the API is bad, or an error in conversion/processing. 

Anyone else see this?

**Comment by schachmat** [comment]
This is probably #102 (a bug in the forecast.io backend). I did not have the time to resolve it yet, if you can contribute, feel free to do so. I renamed the title of this issue to be more exact for the issue.

**Comment by kordianbruck** [comment]
forecast.io is gone and so this bug seems obsolete.
