### ISSUE TITLE
Could not find selected backend "forecast.io"

### ISSUE THREAD

**Issue by kakulukia** [schachmat/wego#110]
and 

# The following options are probably deprecated and not used currently!
location=40.748,-73.985
forecast-api-key=YOUR_FORECAST.IO_API_KEY_HERE

I get those messages when im starting wego with the recommended settings from the readme.
Whats wrong?

**Comment by schachmat** [comment]
Heyho @kakulukia,

I can't see the problem right away. Can you upload the complete `.wegorc` file you are using somewhere?
Also, how did you install wego?

**Comment by shian15810** [comment]
I'm having the same issue, and I can replicate it on  my mac by having wego installed through homebrew (brew install wego), which in turn just execute this ruby script on my mac: https://github.com/Homebrew/homebrew-core/blob/master/Formula/wego.rb

This ruby script install the 2.0 release version of wego, which unfortunately didn't include forecast.io yet. As far as I know, they are quite strict on this, they don't approve any update on those package which is not yet released.

In the meantime, the short way to solved this is to have wego installed through go get. Or you guys can release the newest version too, which in turn will be updated by homebrew then.

**Comment by schachmat** [comment]
Heyho @shian15810, @kakulukia,

Thanks for the explanation!

To fix the issue you could also try to use the wwo-backend, apparently there is a way to get a free API key again (#105).

The next release is planned but a few issues need to be resolved first: https://github.com/schachmat/wego/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0

I'm closing this for now. Feel free to reopen if you have more to add on this issue.
