### ISSUE TITLE
Could not find selected backend "forecast.io"

### ISSUE THREAD

**Issue by dade80vr** [schachmat/wego#119]
Hi. 
I have installed Wego with HomeBrew (Mac), registered to darksky.net (forecast.io redirect), modified .wegorc but got error.
Why?

This is my .wegorc file: 

```
# Show geo coordinates (default false)
aat-coords=false
# BACKEND to be used (default worldweatheronline.com)
backend=forecast.io
# LOCATION to be queried (default New York)
city=Verona
# NUMBER of days of weather forecast to be displayed (default 3)
days=3
# FRONTEND to be used (default ascii-art-table)
frontend=ascii-art-table
# json frontend: do not indent the output (default false)
jsn-no-indent=false
# UNITSYSTEM to use for output.
# Choices are: metric, imperial, si (default metric)
units=metric
# wwo backend: the api KEY to use (default )
wwo-api-key=MYAPIKEY
# wwo backend: the LANGUAGE to request from wwo (default en)
wwo-lang=it
```

Thank you.

**Comment by jeresch** [comment]
I struggled with this for a while today actually.  The homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wego.rb) by default pulls from the binary releases.  The most recent binary release is 2.0, which doesn't have forecast.io support.  You can get the most recent version by
```
brew remove wego
brew install --HEAD wego
```

**Comment by schachmat** [comment]
Good to know, thanks @jeresch !

I should probably put out a new release soon then.

@dade80vr, if that fixed the problem for you, please close this issue.

**Comment by dade80vr** [comment]
Running, thanks @jeresch.
Closing issue.
