### ISSUE TITLE
Malformed response

### ISSUE THREAD

**Issue by thomaswrenn** [schachmat/wego#12]
https://www.dropbox.com/s/fquazbu1n9y8s6r/Screenshot%202015-05-14%2012.42.39.png?dl=0
? 

Have an api key set.

**Comment by schachmat** [comment]
Heyho thomas,

if you can reproduce this, please uncomment line 485 (The Println statement), run `go build` in the project directory, then execute the new binary with `./wego` and paste the resulting output (no screenshot).

--schachmat

**Comment by jakobholmelund** [comment]
I get the same thing.. 

2015/05/14 18:59:39 Malformed response.

**Comment by schachmat** [comment]
@jakobholmelund if you have no API key set up yet, please conform to setup section in the README.

**Comment by jakobholmelund** [comment]
When do i learn to read the fucking manual ? Works perfectly :)

**Comment by schachmat** [comment]
@thomaswrenn can we close this or does the issue still persist? In that case please supply the debug output as described in my first comment above.

**Comment by thomaswrenn** [comment]
{"meta":{"version":1,"status_code":403},"results":{"error":{"type":"KeyError","message":"'`#myAPIKey#`' is not a valid key for 'Free-Weather-API-V2'"}}}

**Comment by thomaswrenn** [comment]
Ah, there's the problem. I was using an API key for "Free-Weather-API" that I already had for worldweatheronline.com instead of for "Free-Weather-API-V2"

**Comment by thomaswrenn** [comment]
Ah, there's the problem. I was using an API key for "Free-Weather-API" that I already had for worldweatheronline.com instead of for "Free-Weather-API-V2"
