### ISSUE TITLE
colorize current time

### ISSUE THREAD

**Issue by spacelama** [schachmat/wego#123]
The frontend should ideally colourise the current timeslot - for instance, at 18:00 on Thursday 2 Nov, "wego -f emoji -d 2 -b json" would highlight the "evening" slot to Thur's listing.

**Comment by schachmat** [comment]
Why? You already have the current conditions on top which are more accurate than the slot for most backends.

**Comment by spacelama** [comment]
It's a defacto standard to colourise the "current" object in many UIs (such as calendars, even "cal" on the commandline), and this enables you to quickly scan your eye over what's current, and what's just about to happen (the next block beyond what's highlighted).  Knowing what the weather's about to do is why we do forecasts!

**Comment by schachmat** [comment]
Hmk, feel free to create a PR, but please make the color configurable.

**Comment by kordianbruck** [comment]
Seemingly no PR has been suggested in 5 years. So closing this as obsolete.
