### ISSUE TITLE
Release 2.1?

### ISSUE THREAD

**Issue by the-maldridge** [schachmat/wego#129]
I'd like to update the version in Void Linux's tree to support the new backends, but I need a release to do this.  Would you consider releasing a new version?

**Comment by Alessandro-Barbieri** [comment]
Same for gentoo, latest version is 2 and I want to use openweathermap

**Comment by davidak** [comment]
ping @schachmat 

https://repology.org/project/wego/versions

**Comment by kordianbruck** [comment]
I've tagged 2.1 for this: https://github.com/schachmat/wego/releases/tag/2.1
