### ISSUE TITLE
Change how temperature is displayed?

### ISSUE THREAD

**Issue by Silent-Hunter** [schachmat/wego#133]
I think it might be better if the feels like temperature is displayed in parenthesis next to the real temperature, instead of how it is now. What do you think of this? Maybe it could be an option in the config.

**Comment by schachmat** [comment]
This is a great idea! Feel free to send me a PR.

**Comment by Silent-Hunter** [comment]
Okay I'll try! I've never used Go before so I may take a while but I will give it a shot.

**Comment by Silent-Hunter** [comment]
#134 There you go, I hope it works.

**Comment by Silent-Hunter** [comment]
Thanks!

**Comment by schachmat** [comment]
Thank **you** for contributing!

Fixed with https://github.com/schachmat/wego/commit/994e4f141759a1070d7b0c8fbe5fad2cc7ee7d45
