### ISSUE TITLE
Switch between fahrenheit and celsius

### ISSUE THREAD

**Issue by nickpetty** [schachmat/wego#14]
Be nice if the option to switch between fahrenheit and celsius was in the .wegorc.

**Comment by schachmat** [comment]
On May 14, 2015 9:05:31 PM GMT+02:00, Nicholas Petty <notifications@github.com> wrote:
>Be nice if the option to switch between fahrenheit and celsius was in
>the .wegorc.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/schachmat/wego/issues/14

Actually it already is. Have a look at the `Imperial` bool.
