### ISSUE TITLE
Weird table indentation

### ISSUE THREAD

**Issue by fly1ngDream** [schachmat/wego#141]
I've read similar issues but haven't found appropriate solution for me. I use kitty with Hasklig font but i'm not sure that it depends on terminal or font
![image](https://user-images.githubusercontent.com/44244245/65248617-1fff9200-dafb-11e9-8a60-1b958f6d0f7f.png)

**Comment by filalex77** [comment]
Related: #135 #137

**Comment by fly1ngDream** [comment]
As i understand, project relies on [go-runewidth](https://github.com/mattn/go-runewidth). And this issue is caused by [this one](https://github.com/mattn/go-runewidth/issues/28)
