### ISSUE TITLE
Expose formatCond method in frontend interface

### ISSUE THREAD

**Issue by Boot-Error** [schachmat/wego#142]
I'm working using wego as a module for https://github.com/wtfutil/wtf where I need to use `formatCond` in `frontends/ascii-art-table`.

Adding a new method in `iface.frontend` interface, which return the rendered text would be a nice addition.

**Comment by kordianbruck** [comment]
Happy to entertain a PR to illustrate the idea, but this isn't what wego is supposed to be used for.
