### ISSUE TITLE
can't find backend 'openweathermap'

### ISSUE THREAD

**Issue by hemna** [schachmat/wego#144]
Just installed wego via 
brew install wego

ran wego, edited .wegorc and set

```
# BACKEND to be used (default worldweatheronline.com)
backend=openweathermap
```

ran wego 

```
└─[$] <> wego
2020/03/31 14:53:01 Could not find selected backend "openweathermap"
```

**Comment by aki601** [comment]
openweathermap.org it is also not working

**Comment by kuanhulio** [comment]
Try running
```
brew remove wego
brew install --HEAD wego```

**Comment by nicola-bovolato** [comment]
I've had the same problem yesterday on void-linux. 
The package [points to the latest release](https://github.com/void-linux/void-packages/blob/master/srcpkgs/wego/template), which was in 2016. 

Just install the development version as @kuanhulio suggested or build it from source:

`
go get -u github.com/schachmat/wego
`
