### ISSUE TITLE
Dark Sky API being shut down after 2021

### ISSUE THREAD

**Issue by gileri** [schachmat/wego#145]
According to a [blog post](https://web.archive.org/web/20200331173201/https://blog.darksky.net/), Dark Sky is being bought and will shut down their public API in 2021.

I think it will be needed to set another backend as default, then remove the backend after the API is shut down.

Based on the news coverage and the blog being ["cleaned up"](https://web.archive.org/web/20200309082304/https://blog.darksky.net/) I don't think this is an April fool.

**Comment by skylarmt** [comment]
It's being shut down to current API customers in 2021, but they've already stopped taking new registrations.

**Comment by Weetile** [comment]
Is there a possibility of wego being reprogrammed to use the OpenWeatherMap API instead of the Dark Sky API?

**Comment by kordianbruck** [comment]
Yep, we'll need to figure out something new. I'll have a look around, maybe there is something easy and neat available these days. For now I'll close this bug.

**Comment by zdzichu** [comment]
FWIW, OpenWeatherMap has DarkSky compatible API now: https://openweathermap.org/darksky-openweather
Wego already has dedicated OWM backend, but it looks like OWM OneCall provides more data.

**Comment by kordianbruck** [comment]
Yeah, I'd rather add a OWM onecall backend (or extend the existing one) rather than keep the DarkSky layer in place. Seems a bit less of a maintenance burden. If you want to give it a try, I'm happy to review.
