### ISSUE TITLE
Question/Enhancement: Please add local build instructions

### ISSUE THREAD

**Issue by reportaman** [schachmat/wego#149]
Hi there,

Please add build-file/ build-instructions. I am quite new to Go, and would like to experiment with new frontends, and backbends of wego module to begin with.

I downloaded both ingo and wego repos, and added them to /src under my $GOPATH directory (and removed suffix -master from the dir names). I am able to compile ingo with ``go tool compile in.go``, but compiling wego gives import error on every go file located in subdirectories (like "backend", "frontend") of wego's main directory. No suggestion online seems to be helpful. I intend to make local changes and compile this module, and ideally install it locally.

Thanks!

**Comment by kordianbruck** [comment]
You have to check the repo out to the right folder as well, because the path bears importance. e.g.: `~/go/src/github.com/schachmat/wego` on my system.

Then you can use `go run main.go` to run the program. You might need to run `go mod download` first to get any dependencies.
