### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by naciacia** [schachmat/wego#154]
I have run `go get -u github.com/schachmat/wego`, typed `wego`, and got command not found.

**Comment by reportaman** [comment]
requires "go" language: https://golang.org. Also, the method has ``go get`` method is deprecated now, though it will still install correctly. In future, the equivalent method would be ``go install ...``

**Comment by maxreuben** [comment]
Try including the go/bin folder to the $PATH like so: `export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin`
