### ISSUE TITLE
"Could not find selected backend 'forecast.io'?"

### ISSUE THREAD

**Issue by GitHubQueenn** [schachmat/wego#157]
Trying to get WeGo on Windows 10....So far, I have installed NixOS and WSL2 via Powershell and when I run:

`go get -u github.com/schachmat/wego`
`export PATH=~/go/bin:$PATH`
`wego`

I get "Could not find selected backend forecast.io" after "wego" tries to execute. Please help.

**Comment by ivanlan9** [comment]
On Ubuntu 18.04 and 20.04 both, I get the same error. Makes no difference if I install from githup or building. Does not work.

Is this project even being updated anymore?

**Comment by zapyon** [comment]
I have (probably) the same problem in Ubuntu 22.04:
While "go get -u github.com/schachmat/wego" doesn't work, generating wego does.
But running it, gives me

2022/07/09 09:47:01 Could not find selected backend "forecast.io"

too.

Xubuntu 22.04
go version go1.18.1 linux/amd64

Any hints?

**Comment by asyapluggedin** [comment]
same issue for me. macos monterey 12.4 go1.18.4 darwin/amd64
