### ISSUE TITLE
wegorc file does not generate

### ISSUE THREAD

**Issue by YGameRRYT** [schachmat/wego#163]
Platform info:
MacOS Ventura 13.0.1
M1 MacBook Air 2020
M1 Apple Silicon Chip 16GB ram

So basically what happens is that whenever I follow the instructions, then when it tells me to 'input wegorc command then when it shows an error (I Know it's supposed to) and it also says that it generates the wegorc file, but it doesn't so I can't find the config.

**Comment by kordianbruck** [comment]
Please provide reproduction instructions and your platfrom/version information. Otherwise there isn't much I can do here.

**Comment by YGameRRYT** [comment]
> Please provide reproduction instructions and your platfrom/version information. Otherwise there isn't much I can do here.

I have now provided info

**Comment by YGameRRYT** [comment]
bump

**Comment by kordianbruck** [comment]
Where did you look for the config? I can't reproduce this on linux, so it might be some different folder on macos. Probably related: #161
