### ISSUE TITLE
Incorrect usage of degrees with Kelvin

### ISSUE THREAD

**Issue by ghost** [schachmat/wego#170]
It is incorrect to use degrees with Kelvin (see [BIPM (archived)](https://web.archive.org/web/20141007053944/http://www.bipm.org/en/publications/si-brochure/kelvin.html), [Common mistakes when using the metric system](https://www.nayuki.io/page/common-mistakes-when-using-the-metric-system#degree-sign-word)).

To reproduce: Set `units=si` and query weather information for any location.

Example screenshot:

<img width="1017" alt="Screenshot 2023-07-19 at 14 41 25" src="https://github.com/schachmat/wego/assets/102564844/65dac40a-e4b0-417c-b938-494806318e8e">

**Comment by Madraceee** [comment]
Hey, Is this issue still open, Can i work on it ?
