### ISSUE TITLE
[Feature Request] Open-Meteo Backend Support

### ISSUE THREAD

**Issue by Penaz91** [schachmat/wego#171]
Greetings!

I've been using your app for my Conky setup for a few months and it works Wonderfully!

It would be great if it had support for Open-Meteo: https://open-meteo.com/en/docs

It seems there is support for high-resolution forecasts with the ECMWF Endpoints, which is really interesting in my opinion.

I would make the backend myself, but I have absolutely zero experience with Go, so I thought I would just throw the idea out there in case someone is interested.

Thank you for your attention!

**Comment by kordianbruck** [comment]
Added in https://github.com/schachmat/wego/pull/186 - will release probably after hacktoberfest.
