### ISSUE TITLE
No api_key specified

### ISSUE THREAD

**Issue by lacombar** [schachmat/wego#19]
After building `wego` with gccgo on Fedora (required as `go` has a known bug, cf https://bugzilla.redhat.com/show_bug.cgi?id=1135152), the following happen:

```
$ gccgo -o wego -g we.go
$./wego
2015/05/14 13:46:31 Malformed response.
```

After uncommenting the debug code, here is the body returned:

```
{"meta":{"version":1,"status_code":403},"results":{"error":{"type":"KeyError","message":"No api_key specified."}}}
```

**Comment by bearfrieze** [comment]
The program won't work before you register an API key and insert it into the config file. See the setup section in the readme for more info.

**Comment by lacombar** [comment]
It might be worthwhile to catch this earlier and avoid the confuse error message. The API key length check should be a hard requirement, not a soft-check as it is currently.

**Comment by schachmat** [comment]
I will probably add a default API key to the config which is generated on the first run. I already asked the OWM team, if this is fine with them. If it is not, then I will merge the warning message.
