### ISSUE TITLE
Cache forecast data

### ISSUE THREAD

**Issue by abesto** [schachmat/wego#23]
`wego` is so awesome, I want to add it to my MOTD. Problem is, it takes ~0.5 second to run, and I feel dirty adding 0.5 startup time to my shell "just" for a weather report. One solution to that would be if `wego` cached data for a while - I don't know what would be a reasonable duration, maybe an hour, maybe a few hours?

Is this something you'd want in `wego`, @schachmat? I'd be happy to hack on it in a few weeks if yes.

**Comment by schachmat** [comment]
I don't think wego is the right place to add caching. It is a tool to receive the most up to date forecast available. For your usecase I recommend a cronjob like `wego > ~/.weather`. Then just `cat` this file in your motd.

**Comment by abesto** [comment]
Fair enough.

Thanks for the tip!
