### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AppoPro** [schachmat/wego#25]
# command-line-arguments
./we.go:293: function ends without a return statement

**Comment by schachmat** [comment]
Heyho @AppoPro, does the last commit fix your issue? My compiler did not complain, so if you happen to use gccgo-go instead of golang-go, please make sure to switch to the later one, because there is another bug #6 related to the gccgo-go package.

**Comment by AppoPro** [comment]
i have installed wheezy package (apt-get install golang)

go version go1.0.2

**Comment by schachmat** [comment]
This may be too old. Please try the version 1.3.3 from jessie and let me know, if that fixes your problem.

**Comment by AppoPro** [comment]
i tried this version and all ok but when i try 
./we London 4
2015/05/15 22:37:55 Malformed response.

**Comment by schachmat** [comment]
This is probably the same as in #12. Read the setup instructions in the README.
