### ISSUE TITLE
Problems with IPv6-only hosts

### ISSUE THREAD

**Issue by WhyNotHugo** [schachmat/wego#28]
```
$ wego
2015/05/17 22:32:30 Get https://api.worldweatheronline.com/free/v2/weather.ashx?q=New+York&format=json&num_of_days=3&tp=3&lang=de: dial tcp 37.220.91.249:443: network is unreachable
```

**Comment by schachmat** [comment]
Heyho @hobarrera,

worldweatheronline does not seem to support IPv6 yet. At least there is no AAAA DNS entry for the API domain. You would have to ask them to support IPv6, I can't fix it.

**Comment by hobarrera** [comment]
I have NAT64, so the server does not need to explicitly support this. Most IPv6 users have transitions mechanisms in place (otherwise, half the internet would be unreachable)

    $ ping6 api.worldweatheronline.com
    PING api.worldweatheronline.com(64:ff9b::25dc:5bf9) 56 data bytes
    64 bytes from 64:ff9b::25dc:5bf9: icmp_seq=1 ttl=43 time=331 ms
    ...

This is a client issue, not server issue.

**Comment by schachmat** [comment]
Hm, from the error message in your first comment it seems the api.worldweatheronline.com domain could not be resolved to an IPv6 address (It resolves to the IPv4 address). Maybe your DNS64 also provides the A record, which it [should not](https://tools.ietf.org/html/rfc6147#section-5.1.6)?

[This golang issue](https://code.google.com/p/go/issues/detail?id=8124) could be related as well.

**Comment by hobarrera** [comment]
> Hm, from the error message in your first comment it seems the api.worldweatheronline.com domain could not be resolved to an IPv6 address (It resolves to the IPv4 address). Maybe your DNS64 also provides the A record, which it should not?

It's providing the IPv6 address, as tested via `dig` and then `curl`.

> This golang issue could be related as well.

Sorry, I was unaware that this was written in golang. golang has known issues with IPv6 (and that's why it's generally not recommended for application need network connectivity). I'm pretty sure it'll be an upstream issue (I actually reported the 2014 issue you liked above, amongst others).

I guess it's sort-of-ok to close this, and keep track of golang/go#8124 and golang/go#5707

**Comment by schachmat** [comment]
I tagged it as invalid, but will leave it open for now so other users can find it quickly.

**Comment by hobarrera** [comment]
Sounds great.

**Comment by kordianbruck** [comment]
Given this is 7 years old, I'm not sure there is any longer a point to keep this open.
