### ISSUE TITLE
Some weather descriptions too long for cell width

### ISSUE THREAD

**Issue by lolstarz** [schachmat/wego#30]
As can be seen in the README image, some of the weather descriptions (such as "Patchy rain nearby") are too wide for the column, and are simply cut off when out of space. In this case, should we truncate the text, increase the column width (if we can do so without maximizing terminal width), or expand the column height and use two rows of text?

![screen shot 2015-05-18 at 5 14 54 pm](https://cloud.githubusercontent.com/assets/12422323/7690465/b3017fd4-fd81-11e4-934d-6afee2978bcf.png)

**Comment by schachmat** [comment]
As you can see, I decided to use truncation.

* It is the simplest one to implement
* Failure or malformed responses cannot clutter up the screen with huge cells
* The displayed part of the text is enough to grasp the meaning

Any other arguments?

**Comment by lolstarz** [comment]
Simple is usually best. It feels a bit awkward to see the mid-word cut, but I do not have a solution other than expanding the cells, which would suffer from the issues you raised. I'm OK with it as-is, but maybe someone has an elegant solution.

**Comment by schachmat** [comment]
I could replace the last character with the UTF8 Ellipsis character: „…“?

**Comment by lolstarz** [comment]
I do think that it's more intuitive with a clear indication that it's being truncated.

**Comment by schachmat** [comment]
Fixed in 66f2ab2a38911c662c0c81cf49945b56025e8a26
