### ISSUE TITLE
Current conditions only has FeelsLike temperature

### ISSUE THREAD

**Issue by lolstarz** [schachmat/wego#33]
Because the API call only returns a true FeelsLike

![screen shot 2015-05-18 at 8 43 03 pm](https://cloud.githubusercontent.com/assets/12422323/7693376/88c5e18e-fd9e-11e4-97ef-d19aede16b28.png)

The current weather condition displays a misleading 0deg on one end of the range.

![screen shot 2015-05-18 at 8 41 56 pm](https://cloud.githubusercontent.com/assets/12422323/7693364/69bbd7a8-fd9e-11e4-943e-16d7294c2845.png)

I think if both the FeelsLike and Temp fields are not valid and present, then we should eliminate the range and only print the single value returned in the API call. Do we have a way to determine if it is a valid return from the API call?

Edited -- misread the json output, issue updated

**Comment by JHoloboski** [comment]
I've actually noticed an issue with their API that may explain this one, in which the field names are actually different depending on if you're using current_condition or just hourly data. The "TempC" field appears as "temp_C" for current_condition and tempC for hourly data. See here:

Current_condition:
![current](http://i.imgur.com/FIKP2pZ.png "current_condition")

Hourly data:
![hourly](http://i.imgur.com/xOZGc9i.png "hourly")

**Comment by schachmat** [comment]
This decrepancy is actually [documented](http://www.worldweatheronline.com/api/docs/local-city-town-weather-api.aspx#current_condition_element). I don't think that is going to change soon, so it is a bug in wego and we have to fix it. The first solution that comes to mind would be adding the `temp_C` to the struct, but always prefer the `tempC`, if it is not `0`. Any Idea how to achieve that better?

**Comment by lolstarz** [comment]
I think it's worth considering a rewrite of the current weather display. It is graphically a different object than the cells of the hourly weather reporting, but because it uses the same `formatCond` it is essentially tightly coupled. If the current weather had its own format methods, then we could simply use the correct temp value directly, and any other future changes don't require tricks to preserve the cell displays.

The downside to this approach is that there would likely be a lot of duplicated print code as the current weather display and the hourly weather displays are (nearly) identical.

**Comment by schachmat** [comment]
I don't think that is a good solution. For the backend-frontend separation I would like to have a single struct to represent a weather condition, be it the current one or the one of a time of day in the future. Since this inconsistency is backend-specific, it should later only be handled by the backend.

**Comment by schachmat** [comment]
Fixed. Thanks for reporting @lolstarz and @JHoloboski.

**Comment by parkr** [comment]
https://github.com/schachmat/wego/commit/1c97c3c0d5ecd1dcc5aaa3bc9934df4dff218065
