### ISSUE TITLE
Colors look broken

### ISSUE THREAD

**Issue by l29ah** [schachmat/wego#35]
https://dump.bitcheese.net/files/apotexu/screenshot-wego.png

**Comment by GeertJohan** [comment]
What does `echo $TERM` return in that terminal?

**Comment by l29ah** [comment]
On Wed, May 20, 2015 at 06:59:34AM -0700, Geert-Johan Riemer wrote:
> What does `echo $TERM` return in that terminal?

rxvt-unicode
Tried TERM=xterm that works for stuff like alsamixer and htop; the colourful zero vanished: https://dump.bitcheese.net/files/usetyci/screenshot-wego-xterm.png

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
Er, zero vanished because i've updated wego.

**Comment by GeertJohan** [comment]
Could it be that your terminal only supports 8 instead of 256 colors? I think the purple 0 you saw was in the 8-color palette...

**Comment by l29ah** [comment]
Yeah.

**Comment by GeertJohan** [comment]
Try setting `TERM` to `rxvt-256color`

**Comment by GeertJohan** [comment]
Could also be related to this: https://bbs.archlinux.org/viewtopic.php?id=102285

**Comment by l29ah** [comment]
I go recompile urxvt w/ 256color support, ok (:

**Comment by GeertJohan** [comment]
:+1:

**Comment by l29ah** [comment]
Maybe the proper report must sound like "traditional terminals support" (:
Thank you!

**Comment by GeertJohan** [comment]
No problem, have fun! :smile:
