### ISSUE TITLE
Fedora/Crosscompiling: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by region51** [schachmat/wego#36]
```
[maxim@localhost bin]$ ./wego
2015/05/22 13:51:48 user: Current not implemented on linux/amd64
```
```
[maxim@localhost ~]$ rpm -q golang
golang-1.4.2-2.fc21.x86_64
```
What's wrong?

**Comment by lolstarz** [comment]
Did you install wego as per the instructions? This looks like an issue with cross-compiling, see:
http://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64
https://code.google.com/p/go/issues/detail?id=6376

as a result of: `usr, err := user.Current()`.

**Comment by region51** [comment]
>Did you install wego as per the instructions? 

`sudo yum install golang git`
```
[maxim@localhost ~]$ export GOPATH=/home/maxim/gocode
[maxim@localhost ~]$ go get github.com/schachmat/wego
[maxim@localhost ~]$ cd ~/gocode/bin
[maxim@localhost bin]$ ./wego
2015/05/22 17:20:23 user: Current not implemented on linux/amd64
```

**Comment by schachmat** [comment]
I'm running a x86_64 gentoo system and I've seen wego work on various debian based systems as well. Can someone using Fedora help?

**Comment by hcavalle** [comment]
I'm running fedora with the following specs::
- Kernel 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- go version go1.4.2 linux/amd64

I installed wego following the instructions in the readme (already had a working go environment). 

I'll try and do some fedora specific figuring on my end, though can't promise I'll be of much help...

**Comment by hcavalle** [comment]
Supposedly compiling with [gccgo] (https://github.com/golang/go/wiki/GccgoCrossCompilation) instead of golang can resolve these issues on fedora, but I don't have gcc setup as a cross compiler for go. And the process isn't quick, [here is a link to sample instructions] (http://www.eglibc.org/archives/patches/msg00078.html).

Hopefully I'll have time to test this out later, or maybe someone else can beat me to it.

**Comment by diogocalgaro** [comment]
I'm using Fedora 22 beta and had no previous go environment on my machine.
I have installed go using **"dnf install golang"** and got the same error.
Then I run **"dnf install gcc-go"** and it worked just fine.
My understanding is that it changed the default compiler to gcc-go in my environment.
When I run **"go env | grep CC"** I got:
> CC="/usr/bin/gcc"

**Comment by hcavalle** [comment]
Nice, I just read that using gccgo to compile would solve the issue. I installed go manually and don't have dnf installed but will give it a try. Thanks @diogocalgaro.

**Comment by schachmat** [comment]
Thanks for finding a solution @diogocalgaro, I'll close this then.

**Comment by region51** [comment]
@diogocalgaro @schachmat 
I installed gcc-go, then what? how to start?

**Comment by wildbi111** [comment]
@ghost So how did you make this work.  I have gccg & golang install on fedora21 and i was getting "Current not implemented on linux/amd64" error but now I get this after following your commands:

../src/github.com/schachmat/wego/we.go:8:31: error: import file ‘github.com/mattn/go-colorable’ not found
  "github.com/mattn/go-colorable"
                               ^
../src/github.com/schachmat/wego/we.go:626:12: error: reference to undefined name ‘colorable’
  stdout := colorable.NewColorableStdout()

**Comment by techtonik** [comment]
code from crypto/ssh/test:
```
func username() string {
	var username string
	if user, err := user.Current(); err == nil {
		username = user.Username
	} else {
		// user.Current() currently requires cgo. If an error is
		// returned attempt to get the username from the environment.
		log.Printf("user.Current: %v; falling back on $USER", err)
		username = os.Getenv("USER")
	}
	if username == "" {
		panic("Unable to get username")
	}
	return username
}
```

**Comment by schachmat** [comment]
Heyho @techtonik,

thanks for the hint, but we already have a better solution, which also works on systems where not even USER is defined by default: You can specify the config file path yourself in WEGORC. I just made the error message more verbose to hint the users to that fix.
