### ISSUE TITLE
Add not 64 bit linux compatible to reqs in README

### ISSUE THREAD

**Issue by hcavalle** [schachmat/wego#41]
Doesn't seem to run on 64 bit linux, should maybe add to reqs on readme.

**Comment by schachmat** [comment]
Works on my and many other 64bit linux machines. Can you give more details? Is your issue related to #6 or #36?

**Comment by hcavalle** [comment]
Ah yes, my mistake it is the same as #36. I'll try and do some digging on the fedora front. My system is running this kernel version:
 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I'll close this and add comments to the existing issue. Thanks for the quick response and redirection!
