### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by ear** [schachmat/wego#44]
I installed it three days ago, got an api key, it was working fine until today, when I get:
```
$ wego
2015/05/30 12:38:13 Get https://api.worldweatheronline.com/free/v2/weather.ashx?key=[…]&q=[…]&format=json&num_of_days=3&tp=3&lang=de: x509: certificate has expired or is not yet valid
```
Is this a server side problem or something we can fix on the client?
Thank you

**Comment by region51** [comment]
This server problems
```
[maxim@localhost ~]$ wego
2015/05/30 14:39:18 Get https://api.worldweatheronline.com/free/v2/weather.ashx?key=78069ef2ba2a9dac2a31556442f79&q=Murmansk&format=json&num_of_days=3&tp=3&lang=en: x509: certificate has expired or is not yet valid
```

**Comment by jirislav** [comment]
This can be temporarily fixed by editing line 280 of we.go file -> rewrite https to http

**Comment by jamesbeebop** [comment]
The site seems to have renewed their cert, I can connect again using https.

**Comment by schachmat** [comment]
Works for me too, they deployed the [new certificate](https://www.ssllabs.com/ssltest/analyze.html?d=api.worldweatheronline.com) a bit too early, but now it is valid.
