### ISSUE TITLE
Get returns EOF, no weather data displayed

### ISSUE THREAD

**Issue by tasmo** [schachmat/wego#48]
Running on Arch Linux I just get the following result without any aplication UI:
`__MY_DATE__ __MY_TIME__ Get https://api.worldweatheronline.com/free/v2/weather.ashx?key=__MY_KEY__&q=Berlin&format=json&num_of_days=3&tp=3&lang=en: EOF`

**Comment by schachmat** [comment]
Heyho, I get the same response currently. This seems to be a problem with the worldweatheronline API, let's hope it will be fixed soon.

**Comment by jamesbeebop** [comment]
This seems to be a problem specifically with their secure server/connection.  Changing the URI to http fixes the issue for me.

**Comment by schachmat** [comment]
works again.
