### ISSUE TITLE
ssl certificate verification errors

### ISSUE THREAD

**Issue by OliverLeitner** [schachmat/wego#50]
hi schachmat

i am getting ssl certificate validation errors from your program...

~/scripts/gocode/bin$ ./wego 
2015/07/05 18:14:02 Get https://api.worldweatheronline.com/free/v2/weather.ashx?key=387c3a12d592ff2062327362d0c22&q=Salzburg&format=json&num_of_days=3&tp=3&lang=de: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO RSA Certification Authority")

your go program isnt the first script im getting this error from, so im guessing the service changed their security settings to exclude the algorithm that your go program uses to access their url.

**Comment by region51** [comment]
@OliverLeitner https://github.com/schachmat/wego/issues/45

**Comment by schachmat** [comment]
#45 exactly. I'll reopen it so people can see it before filing another duplicate.
