### ISSUE TITLE
“No such host” issue

### ISSUE THREAD

**Issue by starkshaw** [schachmat/wego#51]
I already have the API key and the code is working in my Chrome but not in wego, it gives me:

``
2015/07/08 04:53:41 Get https://api.worldweatheronline.com/free/v2/weather.ashx?key=MASKED_API_KEY&q=Dubai&format=json&num_of_days=3&tp=3&lang=en: dial tcp: lookup api.worldweatheronline.com: no such host
``

OS: OS X 10.10.4

**Comment by schachmat** [comment]
How is the code working in chrome?

The failed lookup could be DNS related. Do you have any special setup on your host or router? Are you meybe located behind a firewall at your work place?

**Comment by starkshaw** [comment]
Hey you are right. There is a customized DNS in my settings. I re-ordered my DNS it works.

Thanks!

**Comment by schachmat** [comment]
You're welcome. Closed.
