### ISSUE TITLE
ansiEsc.Split undefined

### ISSUE THREAD

**Issue by daniel2887** [schachmat/wego#59]
I tried installing and got the following error:

$sudo go get github.com/schachmat/wego
#github.com/schachmat/wego
/usr/lib/go/src/pkg/github.com/schachmat/wego/we.go:314: ansiEsc.Split undefined (type *regexp.Regexp has no field or method Split)

So I tried installing "sudo go get github.com/hotei/ansiterm" in hopes of getting ansiEsc support, got no output from that command, assumed it ran successfully (though I didn't see anything in my $GOPATH afterwards). I tried installing wego again, same issue.

My Go version is "go version go1".

This is literally my first interaction with Go, so I don't really know what I'm doing. Any hints?

**Comment by schachmat** [comment]
Heyho @daniel2887,

you just need a newer version of go. v1.3 should be fine.

**Comment by daniel2887** [comment]
Worked. Apparently the Go package from Ubuntu's apt isn't the latest. Downloaded 1.5.1 directly from the Go website. The rest of the install went smoothly.

Thanks for your help, beautiful program - does exactly what I wanted.
