### ISSUE TITLE
Wego crashes with segmentation fault

### ISSUE THREAD

**Issue by ArtemZ** [schachmat/wego#6]
Hello,

I'm trying to launch wego under ubuntu 14.04 x64, but it fails each time I try to launch it with the following error:
```
$ ~/.gocode/bin/wego 
unexpected fault address 0x7f5000000011
fatal error: fault
[signal 0xb code=0x1 addr=0x7f5000000011]

goroutine 3 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [select]:
main.main
	/home/artemz/.gocode/src/github.com/schachmat/wego/we.go:441
```

**Comment by schachmat** [comment]
Heyho Artem,

unfortunately I cannot reproduce this. What is the golang version you're using? Which commit of wego are you using? On master [line 441](https://github.com/schachmat/wego/blob/master/we.go#L441) would be `res, err := http.Get(uri + strings.Join(params, "&"))`.

--schachmat

**Comment by ArtemZ** [comment]
I'm using go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64, commit is 4004fd50072bebfc3ed41eccae1388de83715f39

**Comment by schachmat** [comment]
I cannot find a package named [xgcc](http://packages.ubuntu.com/search?keywords=xgcc&searchon=names) in the ubuntu repositories. The relevant package name would be [golang-go](http://packages.ubuntu.com/trusty/devel/golang-go)

**Comment by mikegioia** [comment]
I got this same error on Ubuntu 14.04. All I see is "core dumped", however. I'm not familiar with go stack traces, but I'd be willing to debug this for you if you have something I can run/test.

**Comment by schachmat** [comment]
As the mentioned line of failure mainly contains the http.Get function, please make sure you are not using an old version of golang. I am using v1.4.2 and cannot reproduce this issue. As far as I can see, Ubuntu 14.04 still uses v1.2.1. Make sure this version is up to date with `sudo apt-get update && sudo apt-get upgrade`. Any further hints on this issue are welcome.

**Comment by mikegioia** [comment]
I just re-installed v1.2.1 and now I just see: `2015/05/14 12:55:54 Malformed response.`

Is there an easy way I can debug this, or is it just a requirement to have 1.4.2 of go? If so, oy vey. This is the LTS Ubuntu :(

**Comment by schachmat** [comment]
See the setup section in the README. Until you have an API key setup, this error message is to be expected.

@ArtemZ does reinstalling golang-go also solve the problem for you?

**Comment by mikegioia** [comment]
Very odd, I removed the package gccgo-go and installed the package golang which produced the "Malformed response" output.

I grabbed an API key, set it in the ~/.wegorc, and then ran "wego" again from the CLI and I get the the weather visual. I run a second time, and I get the core dump!

![screenshot from 2015-05-14 13 12 07](https://cloud.githubusercontent.com/assets/387937/7637323/1ed52da4-fa3b-11e4-9e16-edf1ddf798f4.png)

**Comment by schachmat** [comment]
Do you have a special network connection (vpn, tor, some corporate firewall, …)? Does it fail consistently or randomly?

**Comment by mikegioia** [comment]
Completely randomly. I just ran it 3 times in 3 seconds, then the 4th time it failed. No special network config either.

**Comment by schachmat** [comment]
Can you uncomment the two debug output lines in `main()` and paste the output if any of a failed run?

**Comment by mikegioia** [comment]
Okay I think I know what's going on. When I compile this app with `gccgo-go` (4.9.1) I get the segfaults. When I compile it with the package `golang` (1.2.1) the app runs perfectly. I'm assuming this has something to do with gccgo-go. Which is sad because that's the suggested package that Ubuntu gives you when you type "go get ..." and you don't have the go compiler installed.

Either way, this runs fine on golang1.2.1 on Ubuntu 14.04 with no issues. I could run the segfault tests using gccgo-go for you if you want, but I'd have to do that tonight.

**Comment by schachmat** [comment]
Thanks @mikegioia for helping resolve this issue. You don't have to run the segfault tests. They will probably also indicate a failure in the `http.Get` line.
