### ISSUE TITLE
undefined: runewidth.FillRight when installing

### ISSUE THREAD

**Issue by kaibacorp** [schachmat/wego#63]
Installed wego on my Ubuntu laptop with no issue. However, when I went to install it on my Ubuntu VPS with:
`go get github.com/schachmat/wego`

I received the following error:
`# github.com/schachmat/wego
gocode/src/github.com/schachmat/wego/we.go:456: undefined: runewidth.FillRight`

**Comment by schachmat** [comment]
@kaibacorp please check if you have the latest version of `go-runewidth` installed. The missing function was added in [November 2015](https://github.com/mattn/go-runewidth/commit/d96d1bd051f2bd9e7e43d602782b37b93b1b5666), so you might have an older version lying around. `go get -u github.com/mattn/go-runewidth` should do the trick.

**Comment by kaibacorp** [comment]
Perfect, thanks!

I naively just checked that the go version was the same, didn't think to update sorry!
