### ISSUE TITLE
Can't `go get` or `go install`: import cycle not allowed

### ISSUE THREAD

**Issue by Zeklandia** [schachmat/wego#65]
```
import cycle not allowed
package github.com/schachmat/wego
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports runtime
```

Windows 10 Pro 64-bit, Go 1.6.

Let me know if you need more information

**Comment by Zeklandia** [comment]
I originally had 1.5 installed from Google's site for it, then I used `scoop` to install 1.6. It had the same error both times. I'll try checking my installation and see what I find out.

Thanks!

**Comment by schachmat** [comment]
The [internet suggests](http://stackoverflow.com/questions/27695186/import-cycle-not-allowed-while-running-test-in-golang-example) that something could be wrong with your GOPATH as well.

**Comment by Zeklandia** [comment]
I got it to work after uninstalling and reinstalling Go from Google's site!
