### ISSUE TITLE
City should include state or country for lookup

### ISSUE THREAD

**Issue by RichardLitt** [schachmat/wego#70]
Setting the city to 'Cambridge' output data for the UK, not Massachusetts. While expected, this is still not ideal, as I have to use Boston instead.

**Comment by schachmat** [comment]
When you run wego once with the correct input, you can see the "official uniqe representation" of that city from the backend:
```shell
$ wego "Cambridge, Massachusetts"
Weather for City: Cambridge, United States of America
```
Now just use `"Cambridge, United States of America"` in the config file. If this is what you were looking for, please close the issue.

**Comment by RichardLitt** [comment]
That's useful! Thanks for being so quick, @schachmat. I'm not sure that is the best, though: there are a lot of Cambridge's in the US (https://en.wikipedia.org/wiki/Cambridge_(disambiguation)). I think that it should display: `City: Cambridge, Maine, USA` instead. How can I specify Cambridge, Maine, as opposed to Cambridge, Mass in the config file?

**Comment by schachmat** [comment]
That is strange indeed, that the worldweatheronline API returns the same string ("Cambridge, United STates of America") for the two different locations. However you can still use "Campridge, Massachusetts" and "Cambridge, Maine" in the config file or on the command line to get the desired result.

I have a plan to introduce a select option for ambiguous locations and will keep this annoyance in mind when implementing it.

**Comment by RichardLitt** [comment]
Cool. That is useful. Thank you!
