### ISSUE TITLE
Trouble installing wego - undefined flag.UnquoteUsage

### ISSUE THREAD

**Issue by quantran13** [schachmat/wego#72]
I'm currently on Ubuntu 14.04. I installed go using both golang and gccgo-go, but I could not install wego since perhaps flag.UnquoteUsage is not defined.

Error message when using gccgo-go:

```
# github.com/schachmat/ingo                                                                          │go/src/github.com/schachmat/ingo/in.go:67:20: error: reference to undefined identifier ‘flag.UnquoteUsage’
[quantran1101(x)]                         │   _, usage := flag.UnquoteUsage(f)
```

Error message when using golang:

```
# github.com/schachmat/ingo
go/src/github.com/schachmat/ingo/in.go:67: undefined: flag.UnquoteUsage
```

Thanks.

**Comment by schachmat** [comment]
See the first point under "Dependencies" in the README:

Go 1.5 (You can use [goenv](https://github.com/pwoolcoc/goenv) if your distribution does not support Go 1.5 yet)

Alternatively you could just use the 1.0 release which works with older versions as well.

**Comment by quantran13** [comment]
Go on the Ubuntu's repositories seem to be not the version wego needs. I just manually installed Go 1.5 and it worked now. Thanks a lot!
