### ISSUE TITLE
ingo dependency not properly installed on homebrew go

### ISSUE THREAD

**Issue by NoX1De** [schachmat/wego#74]
You should *really* add to README under dependencies that ingo needs to be installed since it says nowhere that you must install ingo prior to installing wego:

Install ingo **prior** to installing wego
`go get -u github.com/schachmat/ingo`

You also may want to clue users in to how to install go also (prior to installing ingo obviously):

Mac OS X install of go using homebrew
`brew install go`

The readme is really confusing and results in a nasty error message and no clues in the error message that the reason it's not working is because ingo wasn't installed prior to installing wego...also when you run wego on first run without ingo installed it says nothing about the configuration file not being automatically generated and nothing about ingo not being installed so it's super confusing...should probably add a check on execute of wego that verifies ingo is installed.

**Comment by schachmat** [comment]
Heyho @NoX1De,

ingo is automatically installed, since `go get` also resolves dependencies. The go environment cannot even build the `wego` binary without first having `ingo` installed, since it links the binary statically.

How to install Go itself is not in the scope of this project since it varies strongly depending on the platform, architecture, operating system and package management you are using. Lots of guides can be found on the internet.

Can you post the error message you got? I assume it is because of an old version of go (<1.5) and the dependencies in the README clearly state you need Go 1.5.

**Comment by NoX1De** [comment]
That could be...however when I installed go via brew it did *not* install ingo automatically for me and it was driving me nuts...I installed go via homebrew...and brew was up to date at the time.

The error is basically just dumping out a lot of the contents of the wego binary:

> $ wego
> /Users/snip/Gostuff/bin/wego: line 4: York: command not found
> /Users/snip/Gostuff/bin/wego: line 13: wwo-api-key=: command not found
> /Users/snip/Gostuff/bin/wego: line 15: wwo-lang=en: command not found
> /Users/snip/Gostuff/bin/wego: line 19: syntax error near unexpected token `)'
> /Users/snip/Gostuff/bin/wego: line 19: `????????????eH?
> H??W??$??$??$??$?H??H?o0H????H??H??@H????               %H??$????H;A?9
>                                          HǄ$HǄ$H??$?H??$H?kH????
>                                                                 L?+H??$H??$I??I??H??L?L?KL9??k
>                                                                                               L?I)?I)?I??tM?H???G
>                                                                                                                  H?W0H?o8H???H?|H?
>                                                                                                                                   H?H?H?H?KH?OH??$?H?\$ H??$?H?\$(H??$?H?\$0L??$?L?l$8L??$?L?|$@L??$?L?t$HL??$?L?T$PL??$?L?D$XL??$?L?L$`H??$?H?,$H??$?H?Z ??H??$H?\$hH??$pH?D$pH?\$xH??$?H?H??$xH?$H??$?H?H?\?j
>    H??$H??$?L?L?KL9??
>                      L?I)?I)?I??tM?*L??$?L??L??$?L??$?L??$?H??$pH??$xH??$?H??$?L??$?L??H??$?L9?}H??H??$?H?4$H??$?H?TH?D$?e???H??H??$xH???H??$?H???H??$p?=?D?)'

**Comment by NoX1De** [comment]
@schachmat it appears brew installed go 1.6 so it should have automatically installed ingo according to your previous comment...but it did not as far as I can tell.  wego only started working after I manually installed ingo via go and then reinstalled wego via go.  Great program btw! Love the command line weather!...just need to prolly clean up the docs a bit for clairty.

**Comment by schachmat** [comment]
That is indeed unusual and not the error I expected at all. Can you provide more info like the output of `go env`?

**Comment by NoX1De** [comment]
Sure, see below for the `go env` output:

`$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/snip/Gostuff"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"`

**Comment by schachmat** [comment]
Hm, that seems to be fine as well. I renamed the title and will leave this issue open for a while. Maybe some other Mac user can help find the issue.

**Comment by NoX1De** [comment]
That title seems more accurate, we could clear up some confusion if we added a few things to the readme that mac users man need to manually install ingo before wego or something to that effect until the  bug is cleared up.  Nice to see you respond so quickly to issues!

Cheers!

**Comment by schachmat** [comment]
I would rather not add it to the README, because otherwise people with the same problem will not notice this issue. I would like to get it fixed properly and not clutter up the README with workarounds. I hope you (and other users running into this problem) will understand my take on this.

Thanks for reporting!

**Comment by NoX1De** [comment]
Understandable...doesn't really make sense why homebrew go didn't install the ingo dependency (or didn't install it properly)...I'm going to install wego fresh on my other macbook and see if it was something I screwed up (I don't think it is) or if this is a true issue/bug..

**Comment by schachmat** [comment]
please add a `-v` to every `go get` call, it should list the downloads then.

**Comment by NoX1De** [comment]
I did try that on the original macbook just a few minutes ago and it didn't seem to be working...let me try it fresh on the other macbook that will be a fresh install, will post output as long as `-v` is working.

**Comment by NoX1De** [comment]
In installing wego fresh on my other macbook it appears that the whole reason for this is mostly my fault...I believe I incorrectly set the $WEGORC environment variable originally on the original macbook where I had the issue, (I will also note when I had the custom $WEGORC location set the .wegorc config file did not appear to be generated, I had to manually create it) but when I set it back to the default location (essentially $HOME), wego was still not working...so I totally removed it using `unset WEGORC` I then manually installed ingo and then installed wego again.  

My sincere apologies for the mistake(s) on my part here and any confusion I introduced- however there may still be an issue of the config file not being generated if a custom location is set for the .wegorc config file _prior to the first run of wego._ 

`-v` did work for me on the fresh install macbook and it seems to be properly downloading ingo:

` 
go get -v -u github.com/schachmat/wego
github.com/schachmat/wego (download)
github.com/schachmat/ingo (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-runewidth (download)
github.com/schachmat/wego/iface
github.com/schachmat/ingo
github.com/mattn/go-runewidth
github.com/mattn/go-colorable
github.com/schachmat/wego/backends
github.com/schachmat/wego/frontends
github.com/schachmat/wego
`

**Comment by schachmat** [comment]
Hm, I think you set the `WEGORC` variable to point to your wego binary accidentally. When wego was started, it then modified it's binary and this is the reason for the strange error messages from your second comment.

I can also assure you the config file `.wegorc` (or whatever `WEGORC` points to) is generated on the first run. Since the default filename starts with a dot it is just hidden in some file managers. The config file is actually rewritten **every** time wego is executed.

I'm closing this now, if anyone has further problems related to this issue, feel free to reopen again.

**Comment by NoX1De** [comment]
That must have been it...that makes sense, I bet I was trying to add the wego binary into my `PATH` and accidentally set the `WEGORC` to the location of the wego binary...doh...sorry again for the trouble, big ups again to you on such a cool program!
