### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by lakhanmankani** [schachmat/wego#80]
I just ran wego and it gave me information which I assume is incorrect.
![untitled](https://cloud.githubusercontent.com/assets/15609091/13725339/753b1e52-e896-11e5-8b0f-5b5936c10768.png)

**Comment by schachmat** [comment]
Can you reproduce this? I get values 100 times smaller than that (which are probably correct). Enable the `-wwo-debug` flag and please also paste your config file (remove the API key if you don't want other people using it).

**Comment by lakhanmankani** [comment]
After several attempts I am unable to reproduce this. But here is my config file
![untitled](https://cloud.githubusercontent.com/assets/15609091/13730305/ae1c171e-e943-11e5-96fb-83489f7b2eb8.png)

**Comment by schachmat** [comment]
Ok, I'll close this for now. If it happens again, please attach the full output with the `-wwo-debug` flag set.

**Comment by lakhanmankani** [comment]
Ok, thanks for your time!
