### ISSUE TITLE
Worldweatheronline suspending free API keys, need new backends

### ISSUE THREAD

**Issue by schachmat** [schachmat/wego#82]
According to [this post](https://www.facebook.com/worldweatheronline/posts/976625715747451) there will soon be no possibility for new users to get a free API key. Therefore wego needs at least one new [backend](https://github.com/schachmat/wego/wiki/How-to-write-a-new-backend-or-frontend). I don't have much time in the near future, so any help is greatly appreciated.

Here is a list of weather services which should be usable. I will update the list.
- [x] [forecast.io](https://developer.forecast.io/docs/v2) (done, see #83)
  - https
  - location can only be specified as latitude,longitude pair
- [x] [openweathermap](http://openweathermap.org/forecast5)
  - easy interface
  - no https
- [ ] [weatherunlocked](https://developer.weatherunlocked.com/documentation/localweather)
  - https
- [ ] [yourweather](http://api.yourweather.co.uk/index.php?p=a)
  - only XML
  - focused on weather in the UK
  - no https?
- [x] your proposed weather service here

A service which does not require registration / an API key would be nice.

**Comment by pramodk-git** [comment]
A couple of alternatives:
http://api.yourweather.co.uk/index.php?p=a
https://developer.weatherunlocked.com/localweather/pricing

**Comment by schachmat** [comment]
thanks @pramodk-git, I added them to the list. weatherunlocked looks very promising, but for the new default I want a backend with no need for registration, so probably openweathermap.

**Comment by camelinc** [comment]
As far as I can tell, openweathermap also requires registration to receive an API key.

I tried getting forecast.io running, but still have some issues with the frontend. The Forecast Slots are not working correctly atm.
 => camelinc@7318a3cf0304e6de99a1e606e8c00421e309fc4a

- [ ] forecast.io
  - registration needed
  - https
  - json

**Comment by schachmat** [comment]
As a quick hint: You can use the json frontend for debugging. It will show the `iface.Data` struct. I could not try it yet, but I assume it's related to the `iface.Cond.Time` element.

**Comment by camelinc** [comment]
that did quite help. The first working commit is camelinc@36123edb98291314ceb6378edbe04d8f56084494

probably needs some polishing and testing

**Comment by schachmat** [comment]
cool. Is it okay for you, if I pull your commits, squash them to a single one (for a cleaner history) and push them to my repo? You will still be the author of the commit, but I will probably have to do some fixup (you changed the import path).

**Comment by camelinc** [comment]
Sure! Are you going to do the pull or should I open a unified pull request?

**Comment by schachmat** [comment]
I already started the pull and fixes, so there is no need to open a pull request.

**Comment by schachmat** [comment]
First forecast.io backend draft is up, refer to #83 for further status information and discussion.

**Comment by polyzen** [comment]
It would seem 2.0 no longer works with WWO's API (using a trial premium key). Appears to be the same issue as https://github.com/schachmat/wego/pull/81#issuecomment-199148088.

I'm trying to build an Arch Linux package against the release (there is a Git package which works great). Perhaps it's time for a release? :)

**Comment by schachmat** [comment]
Heyho @polyzen,

If you are able to, you are very welcome to help get a 2.1 release ready. Only the second step mentioned in #98 is missing, but I am writing my thesis currently so I don't have much time to think about a good solution for that.

**Comment by schachmat** [comment]
Thanks to @R11baka we now have a openweathermap.org backend! :tada:

**Comment by kordianbruck** [comment]
https://github.com/schachmat/wego/pull/186 added openmeteo which is also completely free and no api-key needed. Might switch there as default.

I think there are enough alternatives now that this issue can be closed.
