### ISSUE TITLE
forecast.io backend progress

### ISSUE THREAD

**Issue by schachmat** [schachmat/wego#83]
I pushed the first version of the forecast.io backend to the [forecast.io branch](https://github.com/schachmat/wego/tree/forecast.io). Some points need to be adressed before merging into master:

- [x] double-check to implement the maximum possible of the [iface](https://godoc.org/github.com/schachmat/wego/iface) in condition
- [x] min- and max-temperature for daily data
- [x] astronomy for daily data
- [x] remove debugging code and commented out code
- [x] restrict return value of `Fetch` to the requested number of days
- [x] add language flag
- [x] add call to time machine api to get "forecast" for the passed time of the current day
- [ ] *(optional)* is there a better possibility to specify location other than a `lat,lon` string?

**Comment by khalilfazal** [comment]
I'm having trouble using the forecast.io backend with that branch. After cloning that branch, building, changing the .wegorc, and running I get:

    $ ./wego 
    2016/04/01 04:25:03 Could not find selected backend "forecast.io"

**Comment by schachmat** [comment]
Hm, works for me. Can you double check you actually built the version with a `backends/forecast.io.go` file and did indeed run this newly built binary instead of an old one? Maybe the build process failed and you ran an old version. Also bear in mind that you have to specify the location as "LAT, LON" for this backend.

**Comment by khalilfazal** [comment]
That couldn't be the case, the binaries are in different places. The wwo one is in my GOROOT and the forecast.io one is in my git directory. How do I specify the location as "LAT, LON"? Do I do something like this in .wegorc?:

    # LOCATION to be queried (default New York)
    city=LAT, LON

**Comment by schachmat** [comment]
yes, but without the space in between. Example for New York:

    city=40.748,-73.985

**Comment by schachmat** [comment]
Update! The forecast.io backend should now be in a usable state (see todo list in first post). @camelinc and other interested people: You have 48 hours to test the new backend in the `forecast.io` branch, then I will push the branch onto master.

**Comment by khalilfazal** [comment]
I fixed the issue I was having. My problem was that one has to use the right config key for forecast: `forecast-api-key=`. I don't think that's documented anywhere @schachmat, so make sure it is. Everything works on my end.

**Comment by schachmat** [comment]
Indeed, thanks for the feedback. I just pushed an update, so that a nice error message appears when no API key is specified.

**Comment by Daml** [comment]
Just discover wego today, thanks a lot.

This branch seems to work but lake of doc, so i'v added this in f71e9485e. Using the `location` flag instead of `city` to fit with a39c3f3fe.

**Comment by schachmat** [comment]
Thanks @Daml, I merged your commit and slightly adapted it. The forecast.io branch has now been rebased onto master and is the new default backend. This issue stays open until at least the two non-optional points are fixed.

**Comment by schachmat** [comment]
Closing this since the last remaining todo is tracked by #87.
