### ISSUE TITLE
Backend: JSON?

### ISSUE THREAD

**Issue by matthiasbeyer** [schachmat/wego#84]
Would be nice to be able to pass JSON which was exported with wego right back into wego for viewing, is such a thing possible?

Would be a nice feature, as I think about including wego in [my personal information management suite](https://github.com/matthiasbeyer/imag) and if json import would be possible, I could integrate wego way better IMHO.

**Comment by schachmat** [comment]
Yes, this should be pretty easy to implement, if you want, give it a try and create a PR. Otherwise I will add the `help wanted` label or do it myself soon(tm).

**Comment by schachmat** [comment]
Added in the latest commit. Have fun including it in imag. :)
