### ISSUE TITLE
where did go "wego 0"?

### ISSUE THREAD

**Issue by theist** [schachmat/wego#90]
Hi! sorry if this isn't the appropiate channel.

I updated wego (new laptop) and I had a "wego 0" task to show only current conditions. But it seems isnt working anymore. 

`wego 0` or `wego -d 0` shows current and today forecast, and theres no "only current" reference in `wego --help`

Is there a way to ask wego only current conditions?

**Comment by schachmat** [comment]
Thanks for reporting @theist. This was a bug in the new default backend, which should now be fixed.
