### ISSUE TITLE
Show min/max temperature next to `dateFmt`

### ISSUE THREAD

**Issue by bradleymarques** [schachmat/wego#91]
I have to look at 4 temperature ranges to figure out the minimum and maximum temperatures.  By displaying them in the top 'bar' next to the `dateFmt` output, it would be much easier to see this at a glance.

**Comment by schachmat** [comment]
As explained in #89 I currently have no intention in merging min/max temperatures in the current default frontend. You could either create and submit a completely new frontend containing the info you want or maintain a patched version of one of the existing ones in a fork.
