### ISSUE TITLE
Build FAILURE:  "undefined: flag.UnquoteUsage"

### ISSUE THREAD

**Issue by swdrumm** [schachmat/wego#94]
**What happens:**
Executing:  go get github.com/schachmat/wego
Returns:  src/github.com/schachmat/ingo/in.go:92: undefined: flag.UnquoteUsage

**What should happen:**
Successful build of wego saved as ~/go/bin/wego

**Comment by schachmat** [comment]
See here: https://github.com/schachmat/ingo/issues/2
