### ISSUE TITLE
question

### ISSUE THREAD

**Issue by drduan** [schachmat/wego#95]
2016/08/06 07:27:30 Failed to fetch todays weather data: Failed to fetch todays weather data: Unable to get (https://api.forecast.io/forecast/[CENSORED]/37.8267,-122.423,1470439648?units=ca&lang=en&exclude=minutely,alerts,flags&extend=hourly): http status 400

**Comment by schachmat** [comment]
Heyho,

there seems to be an issue with your API key (which you should never publish online, I censored yours in your message). I tried the same request with mine and it works. Please double check that you use the correct API key.
